<?php

return [
    'name'        => 'Ecommerce',
    'description' => 'Config email templates for Ecommerce',
    'templates'   => [
        'welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'it_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'en_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'fr_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'es_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'de_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'ru_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],
        'ar_welcome'                 => [
            'title'       => 'Welcome',
            'description' => 'Send email to user when they registered an account on our site',
            'subject'     => 'Welcome to {{ site_title }}!',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
            ],
        ],                
        'confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'it_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'en_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'es_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'de_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'fr_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'ru_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'ar_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'en_confirm-email'           => [
            'title'       => 'Confirm email',
            'description' => 'Send email to user when they register an account to verify their email',
            'subject'     => 'Confirm Email Notification',
            'can_off'     => false,
            'variables'   => [
                'verify_link' => 'Verify email link',
            ],
        ],
        'password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'it_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'en_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'es_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'de_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'fr_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'ru_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],
        'ar_password-reminder'       => [
            'title'       => 'Reset password',
            'description' => 'Send email to user when requesting reset password',
            'subject'     => 'Reset Password',
            'can_off'     => false,
            'variables'   => [
                'reset_link' => 'Reset password link',
            ],
        ],        
        'customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'it_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'NeAAA ITALIANOr(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'en_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],  
        'es_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ], 
        'de_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ], 
        'fr_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],  
        'ru_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ], 
        'ar_customer_new_order'      => [
            'title'       => 'plugins/ecommerce::email.customer_new_order_title',
            'description' => 'plugins/ecommerce::email.customer_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],          
        'customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'it_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'en_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'es_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'de_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'fr_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ru_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ar_customer_cancel_order'   => [
            'title'       => 'plugins/ecommerce::email.order_cancellation_title',
            'description' => 'plugins/ecommerce::email.order_cancellation_description',
            'subject'     => 'Order cancelled {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name' => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'      => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'it_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'en_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'es_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'de_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'fr_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'ru_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'ar_customer_delivery_order' => [
            'title'       => 'plugins/ecommerce::email.delivery_confirmation_title',
            'description' => 'plugins/ecommerce::email.delivery_confirmation_description',
            'subject'     => 'Order delivering {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'        => 'plugins/ecommerce::ecommerce.customer_name',
                'order_id'             => 'plugins/ecommerce::ecommerce.order_id',
                'order_delivery_notes' => 'Order delivery notes',
            ],
        ],
        'admin_new_order'         => [
            'title'       => 'plugins/ecommerce::email.admin_new_order_title',
            'description' => 'plugins/ecommerce::email.admin_new_order_description',
            'subject'     => 'New order(s) at {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'it_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'en_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'es_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'de_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'fr_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ru_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ar_order_confirm'           => [
            'title'       => 'plugins/ecommerce::email.order_confirmation_title',
            'description' => 'plugins/ecommerce::email.order_confirmation_description',
            'subject'     => 'Order confirmed {{ order_id }}',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],        
        'order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'it_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'en_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'es_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'de_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'fr_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ru_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'ar_order_confirm_payment'   => [
            'title'       => 'plugins/ecommerce::email.payment_confirmation_title',
            'description' => 'plugins/ecommerce::email.payment_confirmation_description',
            'subject'     => 'Payment for order {{ order_id }} was confirmed',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],                                                        
        'order_recover'           => [
            'title'       => 'plugins/ecommerce::email.order_recover_title',
            'description' => 'plugins/ecommerce::email.order_recover_description',
            'subject'     => 'Incomplete order',
            'can_off'     => true,
            'variables'   => [
                'customer_name'    => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'   => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address' => 'plugins/ecommerce::ecommerce.customer_address',
                'shipping_method'  => 'plugins/ecommerce::ecommerce.shipping_method',
                'payment_method'   => 'plugins/ecommerce::ecommerce.payment_method',
                'product_list'     => 'plugins/ecommerce::ecommerce.product_list',
                'order_id'         => 'plugins/ecommerce::ecommerce.order_id',
                'order_token'      => 'plugins/ecommerce::ecommerce.order_token',
            ],
        ],
        'order-return-request'    => [
            'title'       => 'plugins/ecommerce::email.order_return_request_title',
            'description' => 'plugins/ecommerce::email.order_return_request_description',
            'subject'     => 'Order return request',
            'can_off'     => true,
            'variables'   => [
                'customer_name'       => 'plugins/ecommerce::ecommerce.customer_name',
                'customer_phone'      => 'plugins/ecommerce::ecommerce.customer_phone',
                'customer_address'    => 'plugins/ecommerce::ecommerce.customer_address',
                'list_order_products' => 'List of order products',
                'order_id'            => 'plugins/ecommerce::ecommerce.order_id',
            ],
        ],
        'invoice-payment-created' => [
            'title'       => 'Invoice Payment Detail',
            'description' => 'Send a notification to the customer who makes order',
            'subject'     => 'Payment received from {{ customer_name }} on {{ site_title }}',
            'can_off'     => true,
            'enabled'     => false,
            'variables'   => [
                'customer_name' => 'Customer name',
                'invoice_code'  => 'Invoice Code',
                'invoice_link'  => 'Invoice Link',
            ],
        ],
    ],
];
